### ISSUE TITLE
Chat spam

### ISSUE THREAD

**Issue by bobjackson321** [RagedUnicorn/wow-pvpwarn#2]
Is it intended that my chat is constantly filled with information every time i target someone or untarget?

https://i.imgur.com/YyWDOak.png

**Comment by bobjackson321** [comment]
https://i.imgur.com/Pv9mAZi.png

https://i.imgur.com/J9w9qiC.png

**Comment by RagedUnicorn** [comment]
Hi @bobjackson321 

In a release version it is certainly not intended. For now I did not yet create an official release. If I do so you can find it here - [release](https://github.com/RagedUnicorn/wow-pvpwarn/releases)

Or you can watch the repository and get notified automatically.

For now if you still want to use the addon you can manually change 2 lines of code. Have a look in `Code/PVPW_Environment.lua`

```lua
PVPW_ENVIRONMENT = {
  ADDON_NAME = "PVPWarn",
  ADDON_NAME_SHORT = "PVPW",
  ADDON_VERSION = "1.0.0",
  ADDON_IDENTIFIER = "com.ragedunicorn.pvpwarn",
  LOGPARSER_EXPECTED_VERSION = "1.1.1",
  LOG_LEVEL = 4,
  LOG_EVENT = true
}
```
Change the log level to 1 and log event to false

```lua
PVPW_ENVIRONMENT = {
  ADDON_NAME = "PVPWarn",
  ADDON_NAME_SHORT = "PVPW",
  ADDON_VERSION = "1.0.0",
  ADDON_IDENTIFIER = "com.ragedunicorn.pvpwarn",
  LOGPARSER_EXPECTED_VERSION = "1.1.1",
  LOG_LEVEL = 1,
  LOG_EVENT = false
}
```

Make sure to relog once you did that change.

Cheers,
RagedUnicorn
