### ISSUE TITLE
Chat log spam

### ISSUE THREAD

**Issue by rukk1** [RagedUnicorn/wow-pvpwarn#3]
Hi there,

Similar to the previous issue I'm seeing a lot of logs in my chat frame,  I tried the fix you mentioned - which reduced it - but now I'm seeing a lot of logs related to aura gains whilst standing in town.  Using v1.1.0

Thanks

**Comment by RagedUnicorn** [comment]
Hi @rukk1,

In the meantime there is a release. You should take that one and not directly download the whole repository unless you want to work on the code itself.

https://github.com/RagedUnicorn/wow-vanilla-pvpwarn/releases/tag/v1.1.0

Cheers,
RagedUnicorn

**Comment by rukk1** [comment]
Thanks for the response.  So I deleted my existing PVPWarn folder, and replaced it with the contents from the zip in your link.  I'm still seeing constant spam of messages related to aura gains/etc.  The values in the environment file are 1 and false as you previously suggested.

**Comment by RagedUnicorn** [comment]
Sorry I should have been more specific. You also need to do the same step for the dependency LogParser and make sure that you download the package folder (the ones named PVPWarn.zip and LogParser.zip) not the sourcecode.

https://github.com/RagedUnicorn/wow-vanilla-logparser/releases

Cheers,
RagedUnicorn

**Comment by rukk1** [comment]
Looks like that did the trick, thanks for your instructions.

**Comment by RagedUnicorn** [comment]
Not a problem. Not sure if you are interested in wow classic at all but I will definitely update this addon at one point for classic (separate new repository). I should then be able to use twitch for distributing the addon. That should make things easier :)

Cheers,
RagedUnicorn
