### ISSUE TITLE
Show Events for current target only cannot be activated directly.

### ISSUE THREAD

**Issue by nellyeo** [RagedUnicorn/wow-pvpwarn#6]
Hello,

Maybe its just a graphical bug but the case is;

When you try to enable `Show Events for current target only` when `Ignore events while player is dead` is not selected it doesn't get activated.

But when you enable `Ignore events while player is dead` option, then you are able to enable `Show Events for current target only` option.

Tested build: 1.12.1 5875

Steps to reproduce;
1 - /pvpw opt
2 - Select Show Events for current target only
3 - Close option screen and re-open

**Comment by RagedUnicorn** [comment]
Hi @nellyeo 

Thanks for reporting this. This was indeed an issue. I fixed this with the new version v1.1.1

Cheers,
RagedUnicorn
